export const KB_EMBEDDINGS_QUEUE = 'kb-embeddings'
export const KB_EMBEDDINGS_JOB_NAME = 'generate-page-embeddings'

export const KB_EMBEDDINGS_JOB_ATTEMPTS = 3
export const KB_EMBEDDINGS_JOB_BACKOFF_MS = 5_000
export const KB_EMBEDDINGS_JOB_UPDATE_DEBOUNCE_MS = 5_000
export const KB_EMBEDDINGS_JOB_REMOVE_ON_FAIL = 100

export const KB_EMBEDDINGS_REQUEST_BATCH_SIZE = 64
export const KB_EMBEDDINGS_DB_BATCH_SIZE_DEFAULT = 10
export const KB_EMBEDDINGS_DB_BATCH_SIZE_MAX = 25

export const KB_EMBEDDINGS_DB_BATCH_MAX_BYTES_DEFAULT = 750_000
export const KB_EMBEDDINGS_DB_BATCH_MAX_BYTES_MAX = 10_000_000

export const KB_EMBEDDINGS_REQUEST_MIN_INTERVAL_MS_DEFAULT = 0
export const KB_EMBEDDINGS_REQUEST_MIN_INTERVAL_MS_MAX = 60_000
