# Schedule Content Workflow
name: schedule-content
description: "Schedule a post for future publishing"
author: "BM-Social"

config_source: "{project-root}/.bmad/bm-social/config.yaml"

template: false
instructions: "{installed_path}/instructions.md"

# TODO: Create full instructions.md
# Steps: Select post, choose scheduling method, set timezone, add to queue
