# Market Sizing Workflow - Business Validation Module
# Calculate TAM/SAM/SOM with anti-hallucination compliance

name: market-sizing
description: "Calculate Total Addressable Market, Serviceable Addressable Market, and Serviceable Obtainable Market using multiple methodologies with full source verification"
config_source: "{project-root}/.bmad/bmv/config.yaml"
installed_path: "{project-root}/.bmad/bmv/workflows/market-sizing"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
methodology_guide: "{installed_path}/methodology-guide.md"
default_output_file: "{output_folder}/bmv/market-sizing-{{date}}.md"

# Workflow metadata
workflow_type: document
interaction_mode: research  # Heavy web research required

# Input requirements
inputs:
  - name: idea_intake_path
    type: file_path
    required: false
    description: "Path to idea intake document (for context)"
  - name: market_description
    type: text
    required: true
    description: "Description of the market to size"
  - name: geographic_scope
    type: select
    required: true
    options: [global, north_america, us, europe, apac, latam, custom]
    description: "Geographic scope for market sizing"
  - name: segment_focus
    type: text
    required: false
    description: "Specific segment to focus on (if applicable)"

# Agent assignments
agents:
  primary: market-researcher-agent
  supporting:
    - validation-orchestrator-agent

# MCP tools required
mcp_tools:
  required:
    - jina-ai  # For web search and reading
  optional:
    - context7  # For tech market data

# Anti-hallucination configuration
anti_hallucination:
  min_sources_per_claim: 2
  max_source_age_months: 24
  credibility_threshold: medium
  require_urls: true
  flag_single_source: true
  show_confidence_levels: true

# Output configuration
outputs:
  primary:
    file: "market-sizing-{{date}}.md"
    format: markdown
  data:
    tam_range: "TAM range (low-high)"
    sam_range: "SAM range (low-high)"
    som_projections: "SOM year 1-3"
    confidence_level: "Overall confidence"

# Event triggers
events:
  on_complete:
    - validation.market_sizing.completed
